# Generated by Django 2.2.7 on 2019-11-30 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_auto_20191130_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank=True, default=None, upload_to='post_img'),
            preserve_default=False,
        ),
    ]
