# Generated by Django 2.2.7 on 2019-12-01 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0008_comments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
