# Generated by Django 2.2.7 on 2019-11-29 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='birth_date',
            field=models.DateField(null=True),
        ),
    ]
