# Generated by Django 2.2.7 on 2019-11-30 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofileinfo_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='profile_image',
            field=models.ImageField(null=True, upload_to='profile_img'),
        ),
    ]
